steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/sky-edu-school-lists:latest', '.']
    dir: 'sky-edu-school-lists'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/sky-edu-school-lists:latest']

  # Update the Cloud Run Job with the new image
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'update'
      - 'sky-edu-school-lists'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/sky-edu-school-lists:latest'
      - '--region'
      - 'us-central1'
      - '--task-timeout'
      - '21600s'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/sky-edu-school-lists:latest'

options:
  logging: CLOUD_LOGGING_ONLY